@module tankgame

@include programs/test.glsl
@include programs/textured.glsl
@include programs/ground.glsl
@include programs/ground_blend.glsl
@include programs/water.glsl
@include programs/fog.glsl
@include programs/wall.glsl
@include programs/entity.glsl
@include programs/track.glsl
@include programs/lightmap.glsl
@include programs/particle.glsl
@include programs/laser.glsl
@include programs/debug_text.glsl
@include programs/debug_line.glsl
@include programs/debug_line_3d.glsl
@include programs/sdf_text.glsl
@include programs/background.glsl
@include programs/cursor.glsl
@include programs/editor_grid.glsl
@include programs/ui_quad.glsl
@include programs/ui_textured.glsl
